### ISSUE TITLE
I ran into this.

### ISSUE THREAD

**Issue by jasonrichardsmith** [kosssi/ansible-role-apache#3]
raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/ptn107/apache/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
, W:Failed to fetch http://ppa.launchpad.net/ptn107/apache/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
, E:Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jasonrichardsmith** [comment]
Closing.  Pretty sure this was a another package causing the issue.

**Comment by phillpafford** [comment]
having the same issue while running this in vagrant, how did you fix?

**Comment by phillpafford** [comment]
TASK: [kosssi.apache | Add repository to install last Apache version] ********\* 
failed: [192.168.33.97] => {"failed": true, "parsed": false}
BECOME-SUCCESS-dibsuliascbcwakbyhntpweftvnwrmlj
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1431375791.69-71856554126723/apt_repository", line 2519, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1431375791.69-71856554126723/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/ptn107/apache/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.
OpenSSH_5.9p1, OpenSSL 0.9.8zd 8 Jan 2015
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.33.97 closed.

FATAL: all hosts have already failed -- aborting
